RaycastUtil = {
	MASK = {
		TRIGGER_COMBINES = 4194304,
		GROUND_TIP_BLOCKING = 524288,
		NON_PUSHABLE_2 = 4,
		COMBINES = 128,
		TRIGGER_CUTTERS = 67108864,
		TRIGGER_DYNAMIC_OBJECTS = 16777216,
		TRIGGER_FORK = 134217728,
		TRIGGER_ANIMALS = 268435456,
		STATIC_WORLD_1 = 8,
		TRIGGER_FILLABLES = 8388608,
		KINEMATIC_OBJECTS_NO_COLLISION = 1073741824,
		DYNAMIC_OBJECTS = 4096,
		TRAILERS = 256,
		STATIC_WORLD_2 = 16,
		AI_BLOCKING = 32,
		DYNAMIC_OBJECT_MACHINES = 8192,
		TRIGGER_PLAYER = 1048576,
		NON_PUSHABLE_1 = 2,
		TRACTORS = 64,
		TRAFFIC_VEHICLES_BLOCKING = 33554432,
		TRIGGER_TRACTORS = 2097152
	}
}
RaycastUtil.MASK_TERRAIN_DELTA = RaycastUtil.MASK.NON_PUSHABLE_1 + RaycastUtil.MASK.STATIC_WORLD_1
RaycastUtil.MASK_TRACTORS = RaycastUtil.MASK.NON_PUSHABLE_1 + RaycastUtil.MASK.TRACTORS + RaycastUtil.MASK.DYNAMIC_OBJECT_MACHINES + RaycastUtil.MASK.TRIGGER_TRACTORS
RaycastUtil.MASK_COMBINES = RaycastUtil.MASK.NON_PUSHABLE_1 + RaycastUtil.MASK.COMBINES + RaycastUtil.MASK.DYNAMIC_OBJECT_MACHINES + RaycastUtil.MASK.TRIGGER_COMBINES
RaycastUtil.MASK_FILLABLES = RaycastUtil.MASK.NON_PUSHABLE_1 + RaycastUtil.MASK.TRAILERS + RaycastUtil.MASK.DYNAMIC_OBJECT_MACHINES + RaycastUtil.MASK.TRIGGER_FILLABLES
RaycastUtil.MASK_TOOLS = RaycastUtil.MASK.NON_PUSHABLE_1 + RaycastUtil.MASK.DYNAMIC_OBJECT_MACHINES
RaycastUtil.MASK_CUTTERS = RaycastUtil.MASK.NON_PUSHABLE_1 + RaycastUtil.MASK.DYNAMIC_OBJECTS + RaycastUtil.MASK.DYNAMIC_OBJECT_MACHINES + RaycastUtil.MASK.TRIGGER_CUTTERS
RaycastUtil.MASK_TOOLS_NO_TERRAIN_COLLISION = RaycastUtil.MASK.NON_PUSHABLE_2 + RaycastUtil.MASK.DYNAMIC_OBJECT_MACHINES
RaycastUtil.MASK_PUSHABLE_DYNAMIC_OBJECTS = RaycastUtil.MASK.STATIC_WORLD_1 + RaycastUtil.MASK.DYNAMIC_OBJECTS + RaycastUtil.MASK.DYNAMIC_OBJECT_MACHINES + RaycastUtil.MASK.TRIGGER_DYNAMIC_OBJECTS
RaycastUtil.MASK_TERRAIN_PICKING = RaycastUtil.MASK.AI_BLOCKING + RaycastUtil.MASK.TRACTORS + RaycastUtil.MASK.COMBINES + RaycastUtil.MASK.TRAILERS + RaycastUtil.MASK.DYNAMIC_OBJECTS
RaycastUtil.MASK_TERRAIN = 270532606

function RaycastUtil.getCameraPickingRay(cursorX, cursorY, cameraNode)
	local camX, camY, camZ = getWorldTranslation(cameraNode)
	local pickX, pickY, pickZ = unProject(cursorX, cursorY, 1)
	local dirX = pickX - camX
	local dirY = pickY - camY
	local dirZ = pickZ - camZ

	return camX, camY, camZ, dirX, dirY, dirZ
end
